name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  release_tag:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      new_tag: ${{ steps.next_tag_version.outputs.new_tag }}
    steps:
      - name: Increment tag version
        uses: mathieudutour/github-tag-action@v6.2
        id: next_tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Create Release
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next_tag_version.outputs.new_tag }}
          release_name: ${{ steps.next_tag_version.outputs.new_tag }}
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build Android release
        run: |
          cd android
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
  release:
    name: Release APK
    needs: [apk, release_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4.3.0
        with:
          name: app-release.apk
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release_tag.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: app-release-${{ needs.release_tag.outputs.new_tag }}.apk
          asset_content_type: application/vnd.android.package-archive